### ISSUE TITLE
Blockchain Basics

### ISSUE THREAD

**Issue by yashdev9274** [yashdev9274/Web3-Developer-Path#7]
Add content in [Blockchain](https://github.com/yashdev9274/Web3-Developer-Path/blob/main/my-website/docs/Developers/Blockchain-Basics/Basics.md) directory

> The content should be plagiarism free

**Comment by dakshsinghrathore** [comment]
Hey, @yashdev9274 can you assign this issue to me? am willing to make the required changes in the blockchain directory.

**Comment by yashdev9274** [comment]
yeah sure I'll , but before that I need to work on some issues I'm facing with my main branch, after I resolve that issue I'll assign this one to you.

To know about the updates be in touch.
